-- Supabase/PostgreSQL table for ProductInventoryV6.js product object
-- Schema: inventory
-- Table: product

create schema if not exists inventory;

create table if not exists inventory.product (
    "id" bigint generated by default as identity primary key,
    "code" varchar(255) not null,
    "barcode" varchar(255) not null,
    "name" varchar(255) not null,
    "categoryId" integer not null,
    "supplier" varchar(255),
    "expiryDate" date,
    "status" varchar(255),
    "costPrice" numeric(12,2) not null,
    "sellingPrice" numeric(12,2) not null,
    "quantity" integer not null default 0,
    "unitOfMeasure" varchar(255)
);

-- User requested Supabase without RLS
alter table inventory.product disable row level security;

GRANT USAGE ON SCHEMA inventory TO anon, authenticated, service_role;

GRANT ALL ON ALL TABLES IN SCHEMA inventory TO anon, authenticated, service_role;

insert into inventory.product
(
    "code",
    "barcode",
    "name",
    "categoryId",
    "supplier",
    "expiryDate",
    "status",
    "costPrice",
    "sellingPrice",
    "quantity",
    "unitOfMeasure"
)
values
    ('P001', '1234567890123', 'Product 1', 1, 'Supplier 1', '2024-12-31', 'Active', 10.00, 15.00, 100, 'Piece'),
    ('P002', '1234567890124', 'Product 2', 2, 'Supplier 2', '2025-01-31', 'Active', 20.00, 30.00, 50, 'Piece'),
    ('P003', '1234567890125', 'Product 3', 3, 'Supplier 3', '2024-11-30', 'Inactive', 15.00, 25.00, 200, 'Piece'),
    ('P004', '1234567890126', 'Product 4', 4, 'Supplier 4', '2025-02-28', 'Active', 5.00, 10.00, 150, 'Piece'),
    ('P005', '1234567890127', 'Product 5', 5, 'Supplier 5', '2024-10-31', 'Inactive', 8.00, 12.00, 80, 'Piece');

insert into inventory.product
(
    "code",
    "barcode",
    "name",
    "categoryId",
    "supplier",
    "expiryDate",
    "status",
    "costPrice",
    "sellingPrice",
    "quantity",
    "unitOfMeasure"
)
values
    ('P006', '1234567890128', 'Product 6', 1, 'Supplier 6', '2025-03-31', 'Active', 18.00, 26.00, 70, 'Box'),
    ('P007', '1234567890129', 'Product 7', 2, 'Supplier 7', '2025-04-30', 'Active', 22.00, 35.00, 40, 'Piece'),
    ('P008', '1234567890130', 'Product 8', 3, 'Supplier 8', '2024-09-30', 'Inactive', 6.50, 11.00, 120, 'Pack'),
    ('P009', '1234567890131', 'Product 9', 4, 'Supplier 9', '2025-05-31', 'Active', 30.00, 45.00, 25, 'Bottle'),
    ('P010', '1234567890132', 'Product 10', 5, 'Supplier 10', '2024-08-31', 'Inactive', 12.75, 19.99, 95, 'Piece');
